email:
  recipients:
  - deine.mutter-lel@jgrgurng.com
  - dfsfd.sdfdfs@dfdf.csdc
  sender_email: sd.asdds@tuhh.de
  smtp_port: 23
  smtp_server: mail.tuhh.de
  templates:
    alert:
      body: 'Movement has not been detected since {timestamp}!

        Please check the issue via the web application at: {website_url}.


        Details:

        Session-ID: {session_id}

        Last motion at: {last_motion_time}

        Camera: Index {camera_index}

        Sensitivity: {sensitivity}

        ROI enabled: {roi_enabled}


        Attached is the current webcam image.

        '
      subject: 'CVD-TRACKER-Alert: no motion detected - {timestamp}'
  website_url: http://134.28.91.48:8080
gui:
  auto_open_browser: false
  host: localhost
  port: 8080
  title: CVD-Tracker
  update_interval_ms: 100
logging:
  backup_count: 5
  console_output: true
  file: logs/cvd_tracker.log
  level: INFO
  max_file_size_mb: 10
measurement:
  alert_delay_seconds: 300
  auto_start: false
  image_format: jpg
  image_quality: 85
  image_save_path: ./alerts/
  save_alert_images: true
  session_timeout_minutes: 0
motion_detection:
  background_learning_rate: 0.005
  min_contour_area: 252
  region_of_interest:
    enabled: true
    height: 199
    width: 412
    x: 79
    y: 125
  sensitivity: 0.28
uvc_controls:
  backlight_compensation: 48
  brightness: 0
  contrast: 32
  exposure:
    auto: true
    value: 100
  gain: 6
  gamma: 144
  hue: 0
  saturation: 32
  sharpness: 3
  white_balance:
    auto: true
    value: 4000
webcam:
  camera_index: 0
  default_resolution:
    height: 480
    width: 640
  fps: 30
  resolution:
  - height: 240
    width: 320
  - height: 288
    width: 352
  - height: 480
    width: 640
  - height: 600
    width: 800
  - height: 768
    width: 1024
  - height: 720
    width: 1280
  - height: 960
    width: 1280
  - height: 1024
    width: 1280
  - height: 1080
    width: 1920
