email:
  recipients:
  - willem.dittloff@tuhh.de
  sender_email: willem.dittloff@tuhh.de
  smtp_port: 25
  smtp_server: mail.tuhh.de
  templates:
    alert:
      body: 'Bewegung wird seit {timestamp} nicht erkannt!

        Bitte 체berpr체fen Sie den Fehler 체ber die Webanwendung unter: {website_url}.


        Details:

        Session-ID: {session_id}

        Letzte Bewegung um {last_motion_time}

        Kamera: Index {camera_index}

        Sensitivit채t: {sensitivity}

        ROI aktiv: {roi_enabled}


        Im Anhang finden Sie das aktuelle Webcam-Bild.

        '
      subject: 'CVD-Tracker: Bewegungsalarm - {timestamp}'
  website_url: http://134.28.91.48:8080
gui:
  auto_open_browser: false
  host: localhost
  port: 8080
  title: CVD-Tracker
  update_interval_ms: 100
logging:
  backup_count: 5
  console_output: true
  file: logs/cvd_tracker.log
  level: INFO
  max_file_size_mb: 10
measurement:
  alert_delay_seconds: 300
  auto_start: false
  image_format: jpg
  image_quality: 85
  image_save_path: ./alerts/
  save_alert_images: true
  session_timeout_minutes: 6
motion_detection:
  background_learning_rate: 0.01
  min_contour_area: 500
  region_of_interest:
    enabled: true
    height: 300
    width: 400
    x: 100
    y: 100
  sensitivity: 0.49
uvc_controls:
  backlight_compensation: 61
  brightness: 128
  contrast: 32
  exposure:
    auto: true
    value: 100
  gain: 0
  gamma: 100
  hue: 0
  saturation: 32
  sharpness: 3
  white_balance:
    auto: true
    value: 4000
webcam:
  camera_index: 0
  default_resolution:
    height: 480
    width: 640
  fps: 30
  resolution:
  - height: 240
    width: 320
  - height: 288
    width: 352
  - height: 480
    width: 640
  - height: 600
    width: 800
  - height: 768
    width: 1024
  - height: 720
    width: 1280
  - height: 960
    width: 1280
  - height: 1024
    width: 1280
  - height: 1080
    width: 1920
